services:
  aos-gpt:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: dockerdude63/aos-gpt:latest
    container_name: aos-gpt
    volumes:
      - aos-gpt:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-1776}:1776
    env_file:
      - ../.env
    environment:
      # Defaults (only used if not set in .env)
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN-*}
      - FORWARDED_ALLOW_IPS=${FORWARDED_ALLOW_IPS-*}
      - SCARF_NO_ANALYTICS=${SCARF_NO_ANALYTICS-true}
      - DO_NOT_TRACK=${DO_NOT_TRACK-true}
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY-false}
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  aos-gpt: {}
