services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui-dev
    volumes:
      - open-webui:/app/backend/data
      - ./backend:/app/backend
      - ./src:/app/src
      - ./static:/app/static
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL-http://host.docker.internal:11434}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY-}
      - ENV=dev
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN-*}
      - FORWARDED_ALLOW_IPS=${FORWARDED_ALLOW_IPS-*}
      - SCARF_NO_ANALYTICS=${SCARF_NO_ANALYTICS-true}
      - DO_NOT_TRACK=${DO_NOT_TRACK-true}
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY-false}
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    command: bash -c "cd /app/backend && uvicorn open_webui.main:app --reload --host 0.0.0.0 --port 8080"

volumes:
  open-webui: {}
