services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL-http://host.docker.internal:11434}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY-}
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN-*}
      - FORWARDED_ALLOW_IPS=${FORWARDED_ALLOW_IPS-*}
      # Database
      - DATABASE_URL=${DATABASE_URL-}
      # Vector Database
      - VECTOR_DB=${VECTOR_DB-}
      - PGVECTOR_DB_URL=${PGVECTOR_DB_URL-}
      # Storage (Azure Blob)
      - STORAGE_PROVIDER=${STORAGE_PROVIDER-}
      - AZURE_STORAGE_ENDPOINT=${AZURE_STORAGE_ENDPOINT-}
      - AZURE_STORAGE_CONTAINER_NAME=${AZURE_STORAGE_CONTAINER_NAME-}
      - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY-}
      - AZURE_PIPELINE_CONTAINER_NAME=${AZURE_PIPELINE_CONTAINER_NAME-aos-pipeline}
      # Redis
      - REDIS_URL=${REDIS_URL-}
      # Privacy
      - SCARF_NO_ANALYTICS=${SCARF_NO_ANALYTICS-true}
      - DO_NOT_TRACK=${DO_NOT_TRACK-true}
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY-false}
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui: {}
